/* eslint-disable react/no-unescaped-entities */
"use client";
import Sidebar from "@/components/common/Sidebar/Sidebar";
import Head from "next/head";
import { useState } from "react";

const TermsAndConditions = () => {
  const sections = [
    {
      id: "introduction",
      title: "Introduction",
      content: (
        <section>
          <p className="mb-4">
            The platforms www.klynk.recipes, www.klynk.app,
            www.cookwithsemi.com, www.getriku.com, and appliances Semi, Riku,
            and other associated hardware appliances manufactured or distributed
            which may or may not be embedded with its proprietary software are
            collectively referred to as "platform/s" and are operated by M/s.
            Futuristic Labs Private Limited, (hereinafter referred to as
            "Futuristic Labs", "We", "Our", and "Us") having its registered
            address at "1-107-9/4, MIG 187/8, MVP Colony, Sector -8,
            Visakhapatnam 530017, Andhra Pradesh, India" and having its office
            located at AIKA Plaza, 5th floor, Ayyappa Society, Madhapur,
            Hyderabad, Telangana.
          </p>
          <p className="mb-4">
            Please read the Conditions of Use document carefully before using
            our platforms. By using any of the platform or application, hardware
            appliances embedded with or without our software are collectively
            referred to as platform, you signify your agreement to be bound by
            Futuristic Labs Private Limited’s terms of usage. As described in
            our Privacy policy, we share information with our subsidiaries, our
            service vendors that are either subject to our Privacy policy or
            follow practices at least as protective as those described in our
            Privacy policy. We also share information with third-party service
            providers. For example, we use third-party service providers to
            fulfil orders for products or services, and to deliver packages. For
            any further details on our security practices please read our
            Privacy Policy. For any queries or issues relating to our platforms,
            you can contact us at hello@ftlabs.io
          </p>
        </section>
      ),
    },
    {
      id: "conditions",
      title: "Conditions of Use",
      content: (
        <>
          <p className="mb-4 leading-8">
            Please read these conditions carefully before using our platform. By
            using the platform, you signify your agreement to be bound by these
            conditions. In addition, when you use any current or future
            Futuristic Labs Private Limited services and products you will also
            be subject to the terms, guidelines and conditions applicable to
            that Service terms. These "Conditions of Use" constitute an
            electronic record within the meaning of the applicable law. This
            electronic record is generated by a computer system and does not
            require any physical or digital signatures. Conditions Relating to
            Your Use of Futuristic Labs Private Limited services
          </p>
        </>
      ),
      subSections: [
        {
          id: "account",
          title: "Your Account",
          content: (
            <>
              <p className="mb-4 leading-8">
                If you use the platform or the application of our platform, you
                are responsible for maintaining the confidentiality of your
                account and password and for restricting access to your computer
                to prevent unauthorized access to your account. You agree to
                accept responsibility for all activities that occur under your
                account or password. You should take all necessary steps to
                ensure that the password is kept confidential and secure and
                should inform us immediately if you have any reason to believe
                that your password has become known to anyone else, or if the
                password is being, or is likely to be, used in an unauthorized
                manner. Please ensure that the details you provide us with are
                correct and complete and inform us immediately of any changes to
                the information that you provided when registering. You can
                access and update much of the information you provided us with
                in the Your Account area of the platform. You agree and
                acknowledge that you will use your account on the platform to
                purchase products only for your personal use and not for
                business purposes. Should you wish to order products for
                business purposes, please contact us on hello@ftlabs.io.
                Futuristic Labs Private Limited reserves the right to refuse
                access to the platform, terminate accounts, remove or edit
                content at any time without notice to you.
              </p>
            </>
          ),
        },
        {
          id: "privacy",
          title: "Privacy",
          content: (
            <>
              <p className="mb-4 leading-8">
                Please review our Privacy Policy (hyperlink), which also governs
                your visit to our platform, to understand our practices. The
                personal information / data provided to us by you during the
                course of usage of our platform will be treated as strictly
                confidential and in accordance with the Privacy Policy and
                applicable laws and regulations. If you object to your
                information being transferred or used, please do not use the
                platform.
              </p>
            </>
          ),
        },
        {
          id: "communication",
          title: "E-Platform for Communication",
          content: (
            <>
              <p className="mb-4 leading-8">
                You agree, understand and acknowledge that the platform is an
                online platform that enables you to know about our products and
                purchase products listed on the platform at the price indicated
                therein at any time from any location. You further agree and
                acknowledge that if the order is a preorder, part of any promo
                or campaign run by you, your relationship with us and our
                platform will be governed as per the terms stipulated in that
                preorder, promo or campaign.
              </p>
            </>
          ),
        },
        {
          id: "access",
          title: "Access to our Platforms",
          content: (
            <>
              <p className="mb-4 leading-8">
                We will do our utmost to ensure that availability of the
                platform and our applications will be uninterrupted and that
                transmissions will be error-free. However, due to the nature of
                the Internet, this cannot be guaranteed. Also, your access to
                the platform may also be occasionally suspended or restricted to
                allow for repairs, maintenance, or the introduction of new
                facilities or services at any time without prior notice. We will
                attempt to limit the frequency and duration of any such
                suspension or restriction.
              </p>
            </>
          ),
        },
        {
          id: "license",
          title: "License for Platform Access",
          content: (
            <>
              <p className="mb-4 leading-8">
                Subject to your compliance with these Conditions of Use and
                payment of applicable fees, if any, Futuristic Labs Private
                Limited grants you a limited license to access and make personal
                use of this platform, but not to download (other than page
                caching) or modify it, or any portion of it, except with express
                written consent of Futuristic Labs Private Limited and / or its
                affiliates, as may be applicable. This license does not include
                any resale or commercial use of this platform, applications or
                its contents; any collection and use of any product listings,
                descriptions, or prices; any derivative use of this platform or
                its contents; any downloading or copying of account information
                for the benefit of another party; or any use of data mining,
                robots, or similar data gathering and extraction tools. This
                platform or any portion of this platform (including but not
                limited to any copyrighted material, trademarks, or other
                proprietary information) may not be reproduced, duplicated,
                copied, sold, resold, visited, distributed or otherwise
                exploited for any commercial purpose without express written
                consent of Futuristic Labs Private Limited. You may not frame or
                use framing techniques to enclose any trademark, logo, or other
                proprietary information (including images, text, page layout, or
                form) of Futuristic Labs Private Limited and its affiliates
                without express written consent. You may not use any meta tags
                or any other "hidden text" utilizing our marks, names or
                trademarks without the express written consent of Futuristic
                Labs Private Limited. Any unauthorized use terminates the
                permission or license granted by us as applicable without any
                prior notice. You may not use any of our logo or other
                proprietary graphic or trademark as part of the link without
                express written consent of Futuristic Labs Private Limited.
              </p>
            </>
          ),
        },
        {
          id: "premium",
          title: "Premium Features and Restrictions",
          content: (
            <>
              <p className="mb-4 leading-8">
                The company may offer premium, paid only content, features,
                access and options. The access to certain promotional
                features/content may be restricted as per the discretion of the
                Futuristic Labs Private Limited upon the payment of the
                requisite fee and the platform has the right to modify, amend,
                restrict, suspend any feature, program, access to premium
                content as per the platform’s discretion. The fee for the
                premium features are subject to change upon the sole discretion
                of the platform. For any violation of any of the term of the
                premium program, the platform reserves the right to suspend,
                block, restrict access to the platform with or without any
                notice and in under no case the premium fee paid shall be
                refunded.
              </p>
            </>
          ),
        },
        {
          id: "content",
          title: "Content and Posting",
          content: (
            <>
              <p className="mb-4 leading-8">
                The platform at its discretion may offer the user to post texts,
                articles and multimedia content (images, videos, etc) of their
                own recipes and usage of the company appliances. Such users
                shall be treated as creators. Such creators having and utilizing
                the access to post such recipes and usage of devices in the form
                of audio, images, videos, other multimedia shall be bound by all
                the terms and conditions of the platform and shall abide by the
                rules thus created for posting such content. The company
                reserves the sole right to either approve, reject or suggest
                modifications to such content being submitted for posting on the
                platform. The user also agrees to take the prior consent of the
                company and add a disclaimer in legible, readable format in
                English language that shall disclose that a particular product,
                brand in the content is being endorsed on sponsorship. That the
                content posted should not include or infringe upon any
                copyrighted, trademarked, proprietary information. The user
                shall adhere to forms of language and content decency, make no
                political statements or gestures, make any kind of inciting
                comments, shall not use any profane words or gestures. In the
                event of violation, the company reserves the right to restrict,
                suspend or block all the access as per its discretion. That in
                the event of any user importing his recipes from other
                platforms, the user himself shall ensure that he is not
                violating any content or copyrights policy of such platform it
                is being imported from. Under no circumstances the company shall
                undertake or assume any responsibility for any dispute,
                liability arising from third parties or law enforcement agencies
                in the violation of these polices. The platform shall have all
                the rights to the content posted on its website as if it was
                created and owned by the platform and utilize for their own
                promos, sales etc., without any prior consent of the creator of
                such content.
              </p>
            </>
          ),
        },
        {
          id: "conduct",
          title: "Your Conduct",
          content: (
            <>
              <p className="mb-4 leading-8">
                You must not use the platform in any way that causes, or is
                likely to cause, the platform or access to it to be interrupted,
                damaged or impaired in any way. You understand that you, and not
                Futuristic Labs Private Limited, are responsible for all
                electronic communications and content sent from your computer to
                us and you must use the platform for lawful purposes only. You
                must not use the platform for any of the following: for
                fraudulent purposes, or in connection with a criminal offense or
                other unlawful activity to send, use or reuse any material that
                does not belong to you; or is illegal, offensive (including but
                not limited to material that is sexually explicit content or
                which promotes racism, bigotry, hatred or physical harm),
                deceptive, misleading, abusive, indecent, insulting or
                harassing, blasphemous, defamatory, libelous, obscene,
                pornographic, pedophilic, or menacing; ethnically objectionable,
                disparaging or in breach of copyright, trademark, patent,
                confidentiality, privacy or any other proprietary information or
                right; or is otherwise injurious to third parties; or relates to
                or promotes money laundering or gambling; or is harmful to
                minors in any way; or impersonates another person; or threatens
                the unity, integrity, defense, security or sovereignty of India
                or friendly relations with foreign States or public order or
                causes incitement to the commission of any cognizable offence or
                prevents investigation of any offence or is insulting other
                nation; or objectionable or otherwise unlawful in any manner
                whatsoever; or which consists of or contains software viruses or
                any other computer code, file or program designed to interrupt,
                destroy or limit the functionality of any computer resource,
                political campaigning, commercial solicitation, chain letters,
                mass mailings or any "spam; or is patently false and untrue. to
                cause annoyance, inconvenience or needless anxiety
              </p>
            </>
          ),
        },
        {
          id: "reviews",
          title: "Reviews and Communications",
          content: (
            <>
              <p className="mb-4 leading-8">
                Users of this platform may send communications and submit
                suggestions, ideas, comments, questions, or other information,
                as long as the content is not illegal, obscene, abusive,
                threatening, defamatory, invasive of privacy, infringing of
                intellectual property rights, or otherwise injurious to third
                parties, or objectionable and does not consist of or contain
                software viruses, political campaigning, commercial
                solicitation, chain letters, mass mailings, or any form of
                "spam." In the event a user uses a false e-mail address,
                impersonates any person or entity, or otherwise misleads as to
                the origin of any content. Futuristic Labs Private Limited
                reserves the right (but not the obligation) to remove, refuse,
                delete or edit any content that in the sole judgement of
                Futuristic Labs Private Limited violates these Conditions of use
                and, or terminate your permission to access or use our
                platforms.
              </p>
            </>
          ),
        },
        {
          id: "objectionable",
          title: "Claims against Objectionable Content",
          content: (
            <>
              <p className="mb-4 leading-8">
                You can refer to the product detail page on our platforms in for
                checking any product details provided by us regarding the
                following: <br /> <br /> ● the total price in single figure of
                any good or service, along with the breakup price for the good
                or service, showing all the compulsory and voluntary charges
                such as delivery charges, postage and handling charges,
                conveyance charges and the applicable tax, as applicable. These
                details are available on the invoice issued to you. <br />{" "}
                <br /> ● mandatory notices and information provided by
                applicable laws. <br /> <br /> ● goods and services offered for
                sale by us which are necessary for enabling the consumer to make
                an informed decision at the pre-purchase stage. <br /> <br /> ●
                guarantees related to the authenticity or genuineness of the
                imported products; and. <br /> <br /> ● guarantees or warranties
                applicable to such goods or services. <br /> <br />● Because we
                list multiple products for sale on our platforms, it is not
                possible for us to be aware of the each comment or review that
                is displayed. Accordingly, Futuristic Labs Private Limited
                operates on a "notice and takedown" basis. If you believe that
                any content on the platform is illegal, offensive (including but
                not limited to material that is sexually explicit content or
                which promotes racism, bigotry, hatred or physical harm),
                deceptive, misleading, abusive, indecent, insulting or
                harassing, blasphemous, defamatory, libelous, obscene,
                pornographic, paedophilic, invasive of another’s privacy or
                menacing; ethnically objectionable, disparaging; or in breach of
                a third party’s confidential, proprietary information or right;
                or is otherwise injurious to third parties; or impersonates
                another person; or threatens the unity, integrity, defence,
                security or sovereignty of India or friendly relations with
                foreign States, or public order, or causes incitement to the
                commission of any cognisable offence or prevents investigation
                of any offence or in insulting other nation; or objectionable or
                otherwise unlawful in any manner whatsoever; or which consists
                of or contains software viruses or any other computer code, file
                or program designed to interrupt, destroy or limit the
                functionality of any computer resource; or is patently false and
                untrue (" Objectionable Content "), please notify us immediately
                by emailing us on hello@ftlabs.io. Once this procedure has been
                followed, we will make all reasonable endeavours to remove such
                Objectionable Content complained about within a reasonable time.
              </p>
            </>
          ),
        },
        {
          id: "copyright",
          title: "Copyright and Database Rights",
          content: (
            <>
              <p className="mb-4 leading-8">
                All content included on the platform, such as text, graphics,
                logos, button icons, images, audio clips, digital downloads,
                data compilations, and software, is the property of Futuristic
                Labs Private Limited, its affiliates or its content suppliers
                and is protected by India and international copyright, authors'
                rights and database right laws. The compilation of all content
                on these platforms is the exclusive property of Futuristic Labs
                Private Limited and its affiliates and is protected by laws of
                India and international copyright and database right laws. All
                software used on these platforms is the property of Futuristic
                Labs Private Limited, its affiliates or its software suppliers
                and is protected by India and international copyright and
                author' rights laws. You may not systematically extract/ or
                re-utilise parts of the contents of the platform without
                Futuristic Labs Private Limited and / or its affiliate's (as the
                case may be) express written consent. In particular, you may not
                utilise any data mining, robots, or similar data gathering and
                extraction tools to extract (whether once or many times) for
                re-utilization of any substantial parts of this platform,
                without Futuristic Labs Private Limited and / or its affiliate's
                (as the case may be) express written consent. You may also not
                create and/ or publish your own database that features
                substantial (eg: prices and product listings) parts of this
                platform without Futuristic Labs Private Limited and / or its
                affiliate's (as may be applicable) express written consent.
              </p>
            </>
          ),
        },
        {
          id: "Intellectual Property Claims",
          title: "Intellectual Property Claims",
          content: (
            <>
              <p className="mb-4 leading-8">
                Futuristic Labs Private Limited and all its affiliates, sub
                brands respects the intellectual property of others. If you
                believe that your intellectual property rights have been used in
                a way that gives rise to concerns of infringement, please reach
                out to us on hello@ftlabs.io.
              </p>
            </>
          ),
        },
        {
          id: "trademarks",
          title: "Trademarks",
          content: (
            <>
              <p className="mb-4 leading-8">
                “Klynk”, “Riku”, “Semi” (include all our marks and identifiers)
                and other marks indicated on our platform are trademarks or
                registered trademarks of Futuristic Labs Private Limited or its
                subsidiaries (collectively " Futuristic Labs Private Limited "),
                in the Indian and Other jurisdictions. Our graphics, logos, page
                headers, button icons, scripts and service names are the
                trademarks or trade dress of Futuristic Labs Private Limited.
                Futuristic Labs Private Limited trademarks and trade dress may
                not be used in connection with any product or service that is
                not ours, in any manner that is likely to cause confusion among
                customers, or in any manner that disparages or discredits
                Futuristic Labs Private Limited. All other trademarks not owned
                by Futuristic Labs Private Limited that appear on this platform
                are the property of their respective owners, who may or may not
                be affiliated with, connected to, or sponsored by Futuristic
                Labs Private Limited.
              </p>
            </>
          ),
        },
        {
          id: "disclaimer",
          title: "Disclaimer",
          content: (
            <>
              <p className="mb-4 leading-8">
                You acknowledge and undertake that you are accessing the
                services on the platform and transacting at your own risk and
                are using your best and prudent judgement before entering into
                any transactions through the platform. You further acknowledge
                and undertake that you will use the platform to order products
                only for your personal use and not for business purposes. We
                shall neither be liable nor responsible for any actions or
                inactions taken by you that’s violative of our policy.
              </p>
            </>
          ),
        },
        {
          id: "indemnity",
          title: "Indemnity and Release",
          content: (
            <>
              <p className="mb-4 leading-8">
                You shall indemnify and hold harmless Futuristic Labs Private
                Limited, its subsidiaries, affiliates and their respective
                officers, directors, agents and employees, from any claim or
                demand, or actions including reasonable attorney's fees, made by
                any third party or penalty imposed due to or arising out of your
                breach of these Conditions of Use or any document incorporated
                by reference, or your violation of any law, rules, regulations
                or the rights of a third party. <br /> <br /> You hereby
                expressly release Futuristic Labs Private Limited and/or its
                affiliates and/or any of its officers and representatives from
                any cost, damage, liability or other consequence of any of the
                actions/inactions of the vendors and specifically waiver any
                claims or demands that you may have in this behalf under any
                statute, contract or otherwise.
              </p>
            </>
          ),
        },
        {
          id: "children",
          title: "Children",
          content: (
            <>
              <p className="mb-4 leading-8">
                Use of platform is available only to persons who can form a
                legally binding contract under the Indian Contract Act, 1872. If
                you are a minor i.e. under the age of 18 years, you may use our
                platform only with the involvement of a parent or guardian.
              </p>
            </>
          ),
        },
        {
          id: "communications",
          title: "Communications",
          content: (
            <>
              <p className="mb-4 leading-8">
                When you visit our platform, you are communicating with us
                electronically. You will be required to provide a valid phone
                number while placing an order with us. We may communicate with
                you by e-mail, SMS, phone call or by posting notices on the
                platform or by any other mode of communication. For contractual
                purposes, you consent to receive communications (including
                transactional, promotional and/or commercial messages), from us
                with respect to your use of the platform and/or your order
                placed on the platform.
              </p>
            </>
          ),
        },
        {
          id: "losses",
          title: "Losses",
          content: (
            <>
              <p className="mb-4 leading-8">
                We will not be responsible for any business loss (including loss
                of profits, revenue, contracts, anticipated savings, data,
                goodwill or wasted expenditure) or any other indirect or
                consequential loss that is not reasonably foreseeable to both
                you and us when you commenced using the platform.
              </p>
            </>
          ),
        },
        {
          id: "alterations",
          title: "Alterations to Service",
          content: (
            <>
              <p className="mb-4 leading-8">
                We reserve the right to make changes to our platform, policies,
                and these Conditions of Use at any time. You will be subject to
                the policies and Conditions of Use in force at the time that you
                use the platform or that you order goods from us, unless any
                change to those policies or these conditions is required to be
                made by law or government authority (in which case it will apply
                to orders previously placed by you). If any of these conditions
                is deemed invalid, void, or for any reason unenforceable, that
                condition will be deemed severable and will not affect the
                validity and enforceability of any remaining condition.
              </p>
            </>
          ),
        },
        {
          id: "recipes",
          title: "Recipes and Guided Cooking",
          content: (
            <>
              <p className="mb-4 leading-8">
                The recipes offered by the platform, ingredients and quantities
                suggested on the platform, the activity performed by the
                appliance for cooking the food on the guided mode is done based
                on the recipes available in the public domain on the internet
                and predominant usage. All the care, caution and internal
                verification, independent evaluations are done before offering
                such a recipe, plan, activity of cooking on the guided mode on
                the platform. The user understands and accepts that such a
                recipe, plan, ingredients, quantities, cooking on guided mode
                are suggestive in nature, all care and caution has been taken by
                the platform in suggesting such a recipe, plan and cooking on
                guided mode and the platform does not guarantee the visual
                appeal and taste as displayed and described.
              </p>
            </>
          ),
        },
        {
          id: "events",
          title: "Events Beyond Our Control",
          content: (
            <>
              <p className="mb-4 leading-8">
                We will not be held responsible for any delay or failure to
                comply with our obligations under these conditions if the delay
                or failure arises from any cause which is beyond our reasonable
                control. This condition does not affect your statutory rights.
              </p>
            </>
          ),
        },
        {
          id: "waiver",
          title: "Waiver",
          content: (
            <>
              <p className="mb-4 leading-8">
                If you breach these conditions and we take no action, we will
                still be entitled to use our rights and remedies in any other
                situation where you breach these conditions.
              </p>
            </>
          ),
        },
        {
          id: "governing-law",
          title: "Governing Law and Jurisdiction",
          content: (
            <>
              <p className="mb-4 leading-8">
                These conditions are governed by and construed in accordance
                with the laws of India. You agree, as we do, to submit to the
                exclusive jurisdiction of the courts at Hyderabad, Telangana,
                India.
              </p>
            </>
          ),
        },
        {
          id: "company-details",
          title: "Our Details",
          content: (
            <>
              <p className="mb-4 leading-8">
                This platform and this application is operated by M/s.
                Futuristic Labs Private Limited a private limited, having its
                registered office at 1-107-9/4 MIG 187/8, MVP Colony, Sector -8,
                Visakhapatnam, Andhra Pradesh, India – 530017.
              </p>
            </>
          ),
        },
        {
          id: "software",
          title: "Software Terms",
          content: (
            <>
              <p className="mb-4 leading-8">
                In addition to these Conditions of Use, the terms found in our
                privacy policy apply to any software (including any updates or
                upgrades to the software and any related documentation) that we
                make available to you from time to time for your use in
                connection with our Services
              </p>
            </>
          ),
        },
        {
          id: "sanctions",
          title: "Sanctions",
          content: (
            <>
              <p className="mb-4 leading-8">
                You may not use any of our Service if you are the subject of
                sanctioned nation or enemy country as declared by the union of
                India or of sanctions imposed by the governments of the country
                where you are using our Services. You must comply with all
                restrictions that may apply to goods, software technology and
                services as mandated by the law.
              </p>
            </>
          ),
        },
        {
          id: "Recipe and helps offered on the platform for cooking various dishes:",
          title:
            "Recipe and helps offered on the platform for cooking various dishes:",
          content: (
            <>
              <p className="mb-4 leading-8">
                The recipes on the platform offered for various items, suggested
                ingredients, quantities prescribed and specific usage prescribed
                for specific preparation of any dish, curry or item is only
                suggestive and is based on wide usage and information available
                in the public domain. The platform does not promise any absolute
                guarantee of output to be of any particular taste, feature or
                characteristic and is only suggestive in nature. For auto
                cooking feature of any recipe and for all other features offered
                in any particular product, please refer to the manual and policy
                of that product usage apart from the conditions prescribed
                herein.
              </p>
            </>
          ),
        },
        {
          id: "Notice and Procedure for Making Claims of Right Infringements",
          title:
            "Notice and Procedure for Making Claims of Right Infringements",
          content: (
            <>
              <p className="mb-4 leading-8">
                If you believe that your rights are being infringed, you may
                contact us here hello@ftlabs.io. We respond expeditiously to
                rights owners and their agents who reach out to us to
                communicate concerns about any alleged infringement. <br />{" "}
                <br /> Upon receipt of communication, we may take certain
                actions without any admission as to liability and without
                prejudice to any rights, remedies or defenses, all of which are
                expressly reserved.
                <br /> <br /> Important Warning: giving false, misleading or
                inaccurate information to us through any medium or making a
                false claim to us may result in civil and/or criminal liability.
                <br /> <br />
                If you believe that your rights are being violated by an item or
                information on platform, you may contact <br /> <br />{" "}
                <strong> Name:</strong>
                Goutham Gandhi Nadendla <strong>Email</strong>: hello@ftlabs.io{" "}
                <br /> <br />
                or <br /> <br />
                <strong>
                  M/s. Futuristic Labs Private Limited a private limited, having
                  its registered office at 1-107-9/4 MIG 187/8, MVP Colony,
                  Sector -8, Visakhapatnam, Andhra Pradesh, India - 530017
                </strong>
              </p>
            </>
          ),
        },
        {
          id: "Software Terms",
          title: "Software Terms",
          content: (
            <>
              <p className="mb-4 leading-8">
                <strong>a. Use of the Futuristic Labs Pvt Ltd Software</strong>{" "}
                <br /> <br />
                You may use our Software solely for purposes of enabling you to
                use and enjoy the Services as provided by us, and as permitted
                by the Conditions of Use, these Software Terms and any Terms.
                You may not incorporate any portion of our Software into your
                own programs or compile any portion of it in combination with
                your own programs, transfer it for use with another service, or
                sell, rent, lease, lend, loan, distribute or sub-license the
                Software or otherwise assign any rights to the Software in whole
                or in part. You may not use the Software for any illegal
                purpose. We may cease providing any Software and we may
                terminate your right to use any of our Software at any time
                without any prior notice. Your rights to use the Software will
                automatically terminate without notice from us if you fail to
                comply with any of these Software Terms, the Conditions of Use
                or any other Terms. Additional third party terms contained
                within or distributed with certain Software that are
                specifically identified in related documentation may apply to
                that Software (or software incorporated with our Software) and
                will govern the use of such software in the event of a conflict
                with these Conditions of Use. All software used in any of our
                Service is the property of Futuristic Labs Private Limited
                and/or its affiliates or its software suppliers and protected by
                laws of India including but not limited to any other applicable
                copyright laws.
              </p>
              <p className="mb-4 leading-8">
                <strong>b. Use of Third Party Services</strong> <br /> <br />
                When you use our Software, you may also be using the services of
                one or more third parties, such as a wireless carrier or a
                mobile platform provider. Your use of these third party services
                may be subject to the separate policies, terms of use, and fees
                of these third parties.
              </p>
              <p className="mb-4 leading-8">
                <strong>c. No Reverse Engineering</strong> <br /> <br />
                You may not, and you will not encourage, assist or authorize any
                other person to copy, modify, reverse engineer, decompile or
                disassemble, or otherwise tamper with, our Software, whether in
                whole or in part, or create any derivative works from or of the
                Software and other ancillary material including videos, images,
                data, description, statistics, all and other information.
              </p>
              <p className="mb-4 leading-8">
                <strong>d. Updates</strong> <br /> <br />
                In order to keep the software up-to-date, we may offer automatic
                or manual updates at any time and without notice to you.
              </p>
            </>
          ),
        },
        {
          id: "Conditions Relating to the Sale of Products to You",
          title: "Conditions Relating to the Sale of Products to You",
          content: (
            <>
              <p className="mb-4 leading-8">
                This section deals with conditions relating to the sale of
                products on the platform by us to you.
              </p>
              <p className="mb-4 leading-8">
                <strong>a. Our Contract</strong> <br /> <br />
                Your order is an offer to us to buy the product(s) in your
                order. When you place an order to purchase a product from us,
                you will receive an e-mail confirming receipt of your order and
                containing the details of your order (the "Order Confirmation
                E-mail"). The Order Confirmation E-mail is acknowledgement that
                we have received your order, and does not confirm acceptance of
                your offer to buy the product(s) ordered. We only accept your
                offer, and conclude the contract of sale for a product ordered
                by you, when the product is dispatched to you and an e-mail
                confirmation is sent to you that the product has been dispatched
                to you (the "Dispatch Confirmation E-mail").Your contract is
                with us and you confirm that the product(s) ordered by you are
                purchased for your internal / personal purpose and not for
                re-sale or business purpose. You authorize us to declare and
                provide declaration to any governmental authority on your behalf
                stating the aforesaid purpose of the products ordered by you on
                the platform. <br /> <br />
                You can cancel your order for a product at no cost any time
                before we send the Dispatch Confirmation E-mail relating to that
                product.
              </p>
              <p className="mb-4 leading-8">
                <strong>b. Returns</strong> <br /> <br />
                Please review our Returns Policy, which applies to products sold
                by us.
              </p>
              <p className="mb-4 leading-8">
                <strong>c. Pricing and availability</strong> <br /> <br />
                We list availability information for products sold by us on the
                platform, including on each product information page. Beyond
                what we say on that page or otherwise on the platform, we cannot
                be more specific about availability. Please note that dispatch
                estimates are just that. They are not guaranteed dispatch times
                and should not be relied upon as such. As we process your order,
                you will be informed by e-mail if any products you order turn
                out to be unavailable.
              </p>
              <p className="mb-4 leading-8">
                <strong>d. Taxes</strong> <br /> <br />
                You shall be responsible for payment of all fees/costs/charges
                associated with the purchase of products from us and you agree
                to bear any and all applicable taxes including but not limited
                to VAT/CST, service tax, GST, duties and cesses etc.
              </p>
              <p className="mb-4 leading-8">
                <strong>e. Health & Safety</strong> <br /> <br />
                By purchasing any product from our platform, you acknowledge
                that you have read and understood our Health & Safety Guidelines
                in the manual that comes with the product and further declare to
                conform to the fair usage as per the manual and no liability
                shall be borne by us in deviation of usage as per the manual and
                general prudence leading to any undesired outcome.
              </p>
            </>
          ),
        },
      ],
    },
  ];
  return (
    <div className="min-h-screen bg-gray-100">
      <Head>
        <title>Terms and Conditions - Futuristic Labs Private Limited</title>
        <meta
          name="description"
          content="Terms and Conditions for Futuristic Labs Private Limited platforms and services"
        />
      </Head>
      <main className="container mx-auto px-4 py-8">
        <h1 className="text-3xl font-bold mb-6 text-center lg:ml-40">
          Terms and Conditions
        </h1>
        <Sidebar sections={sections} />
      </main>
    </div>
  );
};

export default TermsAndConditions;
